services:
  - type: web
    name: blockchain-app
    env: python
    region: oregon  # Change region if needed
    plan: free  # or `starter`, `pro`
    buildCommand: >
      apt-get update && apt-get install -y build-essential gcc libopenblas-dev liblapack-dev &&
      pip install --upgrade pip &&
      pip install -r requirements.txt
    startCommand: gunicorn -w 2 -b 0.0.0.0:$PORT backend.app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: ALCHEMY_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 5000  # Render assigns a dynamic port, ensure your app uses `os.environ["PORT"]`
