services:
  - type: web
    name: blockchain-app
    env: python
    region: oregon
    plan: free
    rootDir: backend  # Ensure this is set correctly
    buildCommand: >
      pip install --upgrade pip &&
      pip install -r config/requirements.txt
    startCommand: gunicorn -w 2 -b 0.0.0.0:$PORT app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: ALCHEMY_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 5000
