services:
  - type: web
    name: blockchain-app
    env: python
    region: oregon  # Adjust region if needed
    plan: free  # Can be `starter` or `pro`

    rootDir: backend  # Ensure commands run inside the `backend` directory

    buildCommand: >
  apt-get update && apt-get install -y build-essential gcc libopenblas-dev liblapack-dev &&
  pip install --upgrade pip &&
  pip install -r backend/config/requirements.txt
    startCommand: gunicorn -w 2 -b 0.0.0.0:$PORT app:app  # Fixed import path

    envVars:
      - key: FLASK_ENV
        value: production
      - key: ALCHEMY_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 5000  # Render dynamically assigns ports
